name: Update Messages

on:
  push:
    paths:
      - messages.json

jobs:
  update-messages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Commit and push changes
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-username"
        git add messages.json
        git commit -m "Update messages"
        git push
